---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: nov29-newargocd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nov29-newargocd 
  name: nov29-newargocd
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi